# Generated by Django 5.0.3 on 2024-03-27 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Year',
            fields=[
                ('AcademicYearID', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Book',
            fields=[
                ('DegreeBookID', models.AutoField(primary_key=True, serialize=False)),
                ('NumberOfGraduationDecision', models.CharField(max_length=50)),
                ('GraduationDecisionDate', models.DateField()),
                ('NumberInTheDegreeBook', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('MajorID', models.AutoField(primary_key=True, serialize=False)),
                ('MajorName', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('MajorCode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=50)),
                ('LastName', models.CharField(max_length=50)),
                ('Gender', models.BooleanField()),
                ('DateOfBirth', models.DateField()),
                ('Address', models.CharField(max_length=50)),
                ('Nation', models.CharField(max_length=50)),
                ('Nationality', models.CharField(max_length=50)),
                ('PhoneNumber', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=50, null=True)),
                ('MSSV', models.CharField(max_length=50)),
                ('YearOfAdmission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Degree_Infomation',
            fields=[
                ('DegreeID', models.AutoField(primary_key=True, serialize=False)),
                ('Classification', models.CharField(max_length=50)),
                ('YearOfGraduation', models.CharField(max_length=50)),
                ('SerialNumber', models.CharField(max_length=50)),
                ('DegreeBookID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.degree_book')),
            ],
        ),
        migrations.CreateModel(
            name='Academic_Program',
            fields=[
                ('ProgramID', models.AutoField(primary_key=True, serialize=False)),
                ('ProgramName', models.CharField(max_length=50)),
                ('ModeofStudy', models.CharField(max_length=50)),
                ('DurationOfTraning', models.CharField(max_length=50)),
                ('Description', models.TextField()),
                ('MajorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.major')),
            ],
        ),
        migrations.AddField(
            model_name='degree_book',
            name='StudentID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.student'),
        ),
        migrations.CreateModel(
            name='Year_Based_Academic_Program',
            fields=[
                ('YBAP_ID', models.AutoField(primary_key=True, serialize=False)),
                ('AcademicYearID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.academic_year')),
                ('ProgramID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.academic_program')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='YBAP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.year_based_academic_program'),
        ),
    ]
