# Generated by Django 5.0.3 on 2024-03-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_degree_infomation_degreebookid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
