# Generated by Django 5.0.3 on 2024-03-31 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_delete_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='YBAP_ID',
        ),
    ]
