# Generated by Django 5.0.3 on 2024-04-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_remove_student_ybap_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='academic_program',
            name='ProgramCode',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
