# Generated by Django 5.0.3 on 2024-04-12 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_academic_program_programcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree_book',
            name='StudentID',
        ),
        migrations.RemoveField(
            model_name='degree_infomation',
            name='DegreeBookID',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Degree_Book',
        ),
        migrations.DeleteModel(
            name='Degree_Infomation',
        ),
    ]
