# Generated by Django 5.0.3 on 2024-04-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_degree_book_degree_infomation_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='YBAP_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.year_based_academic_program'),
        ),
    ]
